# Generated by Django 5.1.4 on 2025-01-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(max_length=30)),
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("file", models.FileField(upload_to="media/")),
            ],
        ),
    ]
